sed -i "s/feature_0 /Affix /g" *process
sed -i "s/feature_1 /Throw /g" *process
sed -i "s/feature_2 /Bait /g" *process
sed -i "s/feature_3 /Contain /g" *process
sed -i "s/feature_4 /Pry /g" *process
sed -i "s/feature_5 /Wave-shake /g" *process
sed -i "s/feature_6 /Block /g" *process
sed -i "s/feature_7 /Prop-climb /g" *process
sed -i "s/feature_8 /Dig /g" *process
sed -i "s/feature_9 /Scratch /g" *process
sed -i "s/feature_10 /Pound /g" *process
sed -i "s/feature_11 /Hang /g" *process
sed -i "s/feature_12 /Wipe /g" *process
sed -i "s/feature_13 /Insert-probe /g" *process
sed -i "s/feature_14 /Drop /g" *process
sed -i "s/feature_15 /Reach /g" *process
sed -i "s/feature_16 /Absorb /g" *process
sed -i "s/feature_17 /Drag-roll /g" *process
sed -i "s/feature_18 /Club /g" *process
sed -i "s/feature_19 /Jab-stab /g" *process
sed -i "s/feature_20 /Symbolize /g" *process
sed -i "s/feature_21 /Cut /g" *process
